# Generated by Django 4.1.1 on 2022-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solved',
            field=models.CharField(default='unsolved', max_length=50),
        ),
    ]
