# Generated by Django 4.1.1 on 2022-11-17 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theBlog', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_solved_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
