# Generated by Django 4.1.1 on 2022-11-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0004_post_solved_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='solved',
        ),
        migrations.AddField(
            model_name='post',
            name='solved_by_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
