# Generated by Django 4.1.1 on 2022-11-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0005_remove_post_solved_post_solved_by_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
