# Generated by Django 4.1.1 on 2022-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0006_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
    ]
