# Generated by Django 4.1.1 on 2022-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0007_comment_endorsed_post_endorsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_endorsed_comment',
            field=models.BooleanField(default=False),
        ),
    ]
