# Generated by Django 4.1.1 on 2022-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0008_post_has_endorsed_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_comment',
            field=models.BooleanField(default=False),
        ),
    ]
