# Generated by Django 4.1.1 on 2022-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0009_post_has_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
