# Generated by Django 4.1.1 on 2022-12-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0010_comment_archived_post_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_archived_comment',
            field=models.BooleanField(default=False),
        ),
    ]
