# Generated by Django 4.1.1 on 2022-12-09 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theBlog', '0011_post_has_archived_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(related_name='course_cat', to='theBlog.category')),
                ('staff', models.ManyToManyField(related_name='course_staff', to=settings.AUTH_USER_MODEL)),
                ('ta', models.ManyToManyField(related_name='course_ta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
