# Generated by Django 4.1.1 on 2022-12-09 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theBlog', '0014_alter_post_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
